service: example-flask-api
provider:
  name: aws
  runtime: python3.10
  stage: dev
  region: eu-west-3
  memorySize: 128

plugins:
  - serverless-python-requirements
  - serverless-wsgi

# uniquement necessaire quand on utilise le plugin `serverless-wsgi`
custom:
  wsgi:
    app: api.app # nom du fichier python (sans le .py) - ici on reference `app` qui situe dans `api.py`
    packRequirements: false
    pythonBin: python3


# avec cette config, on a une seule fonction lambda qui gère toutes les routes (flask)
functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
